In [111]:
import numpy as np

In [112]:
#Creating Arrays and Common Methods

In [113]:
python_list = [1,2,3,4,5,6,7]

In [114]:
print(python_list)

[1, 2, 3, 4, 5, 6, 7]


In [115]:
print(type(python_list))

<class 'list'>


In [116]:
numpy_array_demo = np.array(python_list)

In [117]:
print(numpy_array_demo)

[1 2 3 4 5 6 7]


In [118]:
print(type(numpy_array_demo))

<class 'numpy.ndarray'>


In [119]:
python2dArray = [[1336, 1437, 2436], [3380, 3340, 3320], [3360, 3337, 4351], [4377, 4323, 4348]]

In [120]:
print(python2dArray)

[[1336, 1437, 2436], [3380, 3340, 3320], [3360, 3337, 4351], [4377, 4323, 4348]]


In [121]:
print(type(python2dArray))

<class 'list'>


In [122]:
numpy2dArray = np.array(python2dArray)

In [123]:
print(numpy2dArray)

[[1336 1437 2436]
 [3380 3340 3320]
 [3360 3337 4351]
 [4377 4323 4348]]


In [124]:
print(type(numpy2dArray))

<class 'numpy.ndarray'>


In [125]:
np.arange(0,100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [126]:
np.arange(0,100,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [127]:
np.arange(0,100).reshape(10,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [128]:
np.zeros(25)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0.])

In [129]:
np.zeros(25).reshape(5,5)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [130]:
np.ones(25)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1.])

In [131]:
np.ones(25).reshape(5,5)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [132]:
np.ones(25, dtype=int).reshape(5,5)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [133]:
np.eye(11)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [134]:
np.random.rand(17)

array([0.91337457, 0.51226669, 0.04762272, 0.53873064, 0.57709297,
       0.05451663, 0.30053196, 0.27319976, 0.88944207, 0.48794774,
       0.56476714, 0.7616209 , 0.63047912, 0.71123871, 0.47525833,
       0.57146213, 0.78361128])

In [135]:
np.random.randn(7)

array([ 0.99150059,  0.18072595,  0.11736834,  0.63182138,  1.07638096,
       -0.42930143,  1.00011323])

In [136]:
np.random.randint(720000)

113351

In [137]:
np.random.randint(100000, 720000, 25)

array([136524, 652311, 654267, 341842, 221190, 353262, 340518, 209524,
       203680, 319934, 509907, 692630, 123844, 458861, 118253, 641238,
       137359, 292650, 704320, 583539, 554479, 440160, 242921, 105350,
       354309])

In [138]:
A = np.random.randint(100000, 720000, 25).reshape(5,5)

In [139]:
print(A)

[[468905 252537 125472 195664 288616]
 [657102 633535 315605 630335 275687]
 [535887 561530 199645 688508 245719]
 [346753 340397 536618 600143 537804]
 [159475 342924 354213 656326 155870]]


In [140]:
print(f'The smallest value in A is {A.min()}, and is located at position {A.argmin()}')

The smallest value in A is 125472, and is located at position 2


In [141]:
print(f'The largest value in A is {A.max()}, and is located at position {A.argmax()}')

The largest value in A is 688508, and is located at position 13


In [142]:
A.shape

(5, 5)

In [143]:
np.shape(A)

(5, 5)

In [161]:
#Common Operations

In [179]:
A = np.arange(1,25)
B = np.arange(1, 48, 2)
C = np.arange(0,25).reshape(5,5)
D = np.arange(0,25).reshape(5,5)
E = np.arange(1,25).reshape(3,8)
F = np.arange(12)

In [180]:
print(f'A: {A}')
print(f'B: {B}')
print(f'C: {C}')
print(f'D: {D}')
print(f'E: {E}')
print(f'F: {F}')

A: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
B: [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47]
C: [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
D: [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
E: [[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]]
F: [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [181]:
A+B

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50,
       53, 56, 59, 62, 65, 68, 71])

In [182]:
C+D

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48]])

In [183]:
A+7

array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24,
       25, 26, 27, 28, 29, 30, 31])

In [184]:
(A+B)+7

array([ 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57,
       60, 63, 66, 69, 72, 75, 78])

In [185]:
A-B

array([  0,  -1,  -2,  -3,  -4,  -5,  -6,  -7,  -8,  -9, -10, -11, -12,
       -13, -14, -15, -16, -17, -18, -19, -20, -21, -22, -23])

In [186]:
A-7

array([-6, -5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10,
       11, 12, 13, 14, 15, 16, 17])

In [187]:
A*B

array([   1,    6,   15,   28,   45,   66,   91,  120,  153,  190,  231,
        276,  325,  378,  435,  496,  561,  630,  703,  780,  861,  946,
       1035, 1128])

In [188]:
A*7

array([  7,  14,  21,  28,  35,  42,  49,  56,  63,  70,  77,  84,  91,
        98, 105, 112, 119, 126, 133, 140, 147, 154, 161, 168])

In [189]:
A/B

array([1.        , 0.66666667, 0.6       , 0.57142857, 0.55555556,
       0.54545455, 0.53846154, 0.53333333, 0.52941176, 0.52631579,
       0.52380952, 0.52173913, 0.52      , 0.51851852, 0.51724138,
       0.51612903, 0.51515152, 0.51428571, 0.51351351, 0.51282051,
       0.51219512, 0.51162791, 0.51111111, 0.5106383 ])

In [190]:
A/2

array([ 0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,
        6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5, 11. ,
       11.5, 12. ])

In [191]:
A/3

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667,
       2.        , 2.33333333, 2.66666667, 3.        , 3.33333333,
       3.66666667, 4.        , 4.33333333, 4.66666667, 5.        ,
       5.33333333, 5.66666667, 6.        , 6.33333333, 6.66666667,
       7.        , 7.33333333, 7.66666667, 8.        ])

In [192]:
A/4

array([0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 , 2.75,
       3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  , 5.25, 5.5 ,
       5.75, 6.  ])

In [193]:
A/5

array([0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6,
       2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8])

In [194]:
np.matmul(C, D)

array([[ 150,  160,  170,  180,  190],
       [ 400,  435,  470,  505,  540],
       [ 650,  710,  770,  830,  890],
       [ 900,  985, 1070, 1155, 1240],
       [1150, 1260, 1370, 1480, 1590]])

In [195]:
#Universal Functions

In [198]:
np.sqrt(A)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595,
       4.58257569, 4.69041576, 4.79583152, 4.89897949])

In [199]:
np.sqrt(B)

array([1.        , 1.73205081, 2.23606798, 2.64575131, 3.        ,
       3.31662479, 3.60555128, 3.87298335, 4.12310563, 4.35889894,
       4.58257569, 4.79583152, 5.        , 5.19615242, 5.38516481,
       5.56776436, 5.74456265, 5.91607978, 6.08276253, 6.244998  ,
       6.40312424, 6.55743852, 6.70820393, 6.8556546 ])

In [200]:
np.sqrt(C)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ],
       [3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739],
       [3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894],
       [4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949]])

In [201]:
np.sqrt(D)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ],
       [3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739],
       [3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894],
       [4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949]])

In [202]:
np.sqrt(E)

array([[1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
        2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479, 3.46410162, 3.60555128,
        3.74165739, 3.87298335, 4.        ],
       [4.12310563, 4.24264069, 4.35889894, 4.47213595, 4.58257569,
        4.69041576, 4.79583152, 4.89897949]])

In [203]:
np.sqrt(F)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479])

In [208]:
np.log(A)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898, 2.99573227,
       3.04452244, 3.09104245, 3.13549422, 3.17805383])

In [209]:
np.log(E)

array([[0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
        1.79175947, 1.94591015, 2.07944154],
       [2.19722458, 2.30258509, 2.39789527, 2.48490665, 2.56494936,
        2.63905733, 2.7080502 , 2.77258872],
       [2.83321334, 2.89037176, 2.94443898, 2.99573227, 3.04452244,
        3.09104245, 3.13549422, 3.17805383]])

In [210]:
np.log(F)

/var/folders/r3/pdzzngtx1nzc5n6m5_5nm9540000gn/T/ipykernel_48062/3851838312.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(F)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509, 2.39789527])

In [215]:
np.where(F%2==0, 0, F*100)

array([   0,  100,    0,  300,    0,  500,    0,  700,    0,  900,    0,
       1100])

In [216]:
#Indexing a 1-demensional Array

In [217]:
A = np.arange(18)

In [218]:
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [220]:
print(f'A[0]: {A[0]}')
print(f'A[6]: {A[6]}')
print(f'A[17]: {A[17]}')

A[0]: 0
A[6]: 6
A[17]: 17


In [226]:
A[0:12]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [227]:
A[0:12] = 500000

In [228]:
A

array([500000, 500000, 500000, 500000, 500000, 500000, 500000, 500000,
       500000, 500000, 500000, 500000,     12,     13,     14,     15,
           16,     17])

In [229]:
#Indexing 2-demensional Array

In [230]:
B = np.arange(100).reshape(10,10)

In [231]:
B

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [232]:
print(f'0th row and 1st col in B: {B[0, 3]}')
print(f'2nd row and 3rd col in B: {B[2, 3]}')
print(f'4th row and 3rd col in B: {B[4, 3]}')

0th row and 1st col in B: 3
2nd row and 3rd col in B: 23
4th row and 3rd col in B: 43


In [233]:
B[0:5, 3:8]

array([[ 3,  4,  5,  6,  7],
       [13, 14, 15, 16, 17],
       [23, 24, 25, 26, 27],
       [33, 34, 35, 36, 37],
       [43, 44, 45, 46, 47]])

In [234]:
B[0:5, 3:8] = 100

In [235]:
B

array([[  0,   1,   2, 100, 100, 100, 100, 100,   8,   9],
       [ 10,  11,  12, 100, 100, 100, 100, 100,  18,  19],
       [ 20,  21,  22, 100, 100, 100, 100, 100,  28,  29],
       [ 30,  31,  32, 100, 100, 100, 100, 100,  38,  39],
       [ 40,  41,  42, 100, 100, 100, 100, 100,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99]])

In [236]:
#Boolean Array Indexing

In [239]:
C = np.arange(75).reshape(3,25)

In [240]:
C

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74]])

In [241]:
C%2==0

array([[ True, False,  True, False,  True, False,  True, False,  True,
        False,  True, False,  True, False,  True, False,  True, False,
         True, False,  True, False,  True, False,  True],
       [False,  True, False,  True, False,  True, False,  True, False,
         True, False,  True, False,  True, False,  True, False,  True,
        False,  True, False,  True, False,  True, False],
       [ True, False,  True, False,  True, False,  True, False,  True,
        False,  True, False,  True, False,  True, False,  True, False,
         True, False,  True, False,  True, False,  True]])

In [242]:
C%3==0

array([[ True, False, False,  True, False, False,  True, False, False,
         True, False, False,  True, False, False,  True, False, False,
         True, False, False,  True, False, False,  True],
       [False, False,  True, False, False,  True, False, False,  True,
        False, False,  True, False, False,  True, False, False,  True,
        False, False,  True, False, False,  True, False],
       [False,  True, False, False,  True, False, False,  True, False,
        False,  True, False, False,  True, False, False,  True, False,
        False,  True, False, False,  True, False, False]])

In [247]:
C%2 & C%3 == 0 

array([[ True, False,  True,  True,  True,  True,  True, False,  True,
         True,  True,  True,  True, False,  True,  True,  True,  True,
         True, False,  True,  True,  True,  True,  True],
       [False,  True,  True,  True,  True,  True, False,  True,  True,
         True,  True,  True, False,  True,  True,  True,  True,  True,
        False,  True,  True,  True,  True,  True, False],
       [ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True, False,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True, False,  True]])

In [248]:
(C % 2 == 0).sum()

38

In [253]:
C[C%2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74])

In [254]:
C[C%3 == 0]

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72])